# Generated by Django 3.2.6 on 2021-08-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('mobile_no', models.BigIntegerField()),
                ('last_Donated_date', models.DateField()),
            ],
        ),
    ]
