# Generated by Django 3.2.6 on 2021-08-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatno', models.IntegerField(default='')),
                ('buildingno', models.IntegerField(default='')),
                ('ownerName', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('mobile', models.BigIntegerField(default='')),
                ('aadhar', models.BigIntegerField(default='')),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
