# Generated by Django 3.2.6 on 2021-08-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('phone_no', models.BigIntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
