# Generated by Django 3.2.6 on 2021-08-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('building_no', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('mobile_no', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('adhar_no', models.BigIntegerField()),
                ('emailId', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
