# Generated by Django 3.2.6 on 2021-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
    ]
