# Generated by Django 3.2.6 on 2021-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('bulding_no', models.IntegerField()),
                ('owner_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=2000)),
                ('mobile_no', models.BigIntegerField()),
                ('adhar_no', models.BigIntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
