# Generated by Django 3.2.6 on 2021-08-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productdetails', models.CharField(max_length=30)),
                ('sellername', models.CharField(max_length=50)),
                ('m_date', models.IntegerField()),
                ('e_date', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
