# Generated by Django 3.2.6 on 2021-08-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingno', models.BigIntegerField()),
                ('ownername', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mobileno', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('adharno', models.BigIntegerField()),
                ('password', models.BigIntegerField()),
            ],
        ),
    ]
