# Generated by Django 3.2.6 on 2021-08-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('buildingno', models.IntegerField()),
                ('ownername', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mobileno', models.BigIntegerField()),
                ('adhaarno', models.IntegerField()),
                ('emailid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
